runtime: nodejs10
service: test-cornershop

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build

env_variables:
  URL: 'https://api-test-cornershop-dot-cristian-valdivia.ue.r.appspot.com'
