name: Deploy production

on:
  push:
    branches:
      - main

jobs:
  deploy-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    name: Deploy PROD
    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

      - name: Run deployment
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        with:
          args: app deploy app.yaml
